In [1]:
#Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
import io
import os
import csv
import requests
import json

In [2]:
delhi_df = pd.read_csv('June_22_Data/Delhi_jun22_data.csv')

delhi_df.head()

,Unnamed: 0,location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution
0,0,"Aya Nagar, Delhi - IMD",Delhi,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,no2,16.26,µg/m³,28.470691,77.109936,"[{""name"":""Central Pollution Control Board"",""ur..."
1,1,"Aya Nagar, Delhi - IMD",Delhi,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,pm10,27.66,µg/m³,28.470691,77.109936,"[{""name"":""Central Pollution Control Board"",""ur..."
2,2,"Aya Nagar, Delhi - IMD",Delhi,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,pm25,34.23,µg/m³,28.470691,77.109936,"[{""name"":""Central Pollution Control Board"",""ur..."
3,3,"Aya Nagar, Delhi - IMD",Delhi,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,co,650.00,µg/m³,28.470691,77.109936,"[{""name"":""Central Pollution Control Board"",""ur..."
4,4,"Aya Nagar, Delhi - IMD",Delhi,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,o3,25.11,µg/m³,28.470691,77.109936,"[{""name"":""Central Pollution Control Board"",""ur..."

In [3]:
mumbai_df = pd.read_csv('June_22_Data/Mumbai_jun22_data.csv')

mumbai_df.head()

,Unnamed: 0,location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution
0,0,"Vile Parle West, Mumbai - MPCB",Mumbai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,pm10,32.50,µg/m³,19.10861,72.83622,"[{""name"":""Central Pollution Control Board"",""ur..."
1,1,"Vile Parle West, Mumbai - MPCB",Mumbai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,pm25,8.58,µg/m³,19.10861,72.83622,"[{""name"":""Central Pollution Control Board"",""ur..."
2,2,"Vile Parle West, Mumbai - MPCB",Mumbai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,no2,19.41,µg/m³,19.10861,72.83622,"[{""name"":""Central Pollution Control Board"",""ur..."
3,3,"Vile Parle West, Mumbai - MPCB",Mumbai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,co,500.00,µg/m³,19.10861,72.83622,"[{""name"":""Central Pollution Control Board"",""ur..."
4,4,"Vile Parle West, Mumbai - MPCB",Mumbai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,so2,6.23,µg/m³,19.10861,72.83622,"[{""name"":""Central Pollution Control Board"",""ur..."

In [4]:
chennai_df = pd.read_csv('June_22_Data/Chennai_jun22_data.csv')

chennai_df.head()

,Unnamed: 0,location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution
0,0,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,no2,3.27,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
1,1,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,so2,3.85,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
2,2,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,co,1010.00,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
3,3,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,pm25,6.35,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
4,4,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,o3,0.00,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."

In [5]:
patna_df = pd.read_csv('June_22_Data/Patna_jun22_data.csv')

patna_df.head()

,Unnamed: 0,location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution
0,0,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,pm10,36.83,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
1,1,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,so2,3.26,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
2,2,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,no2,0.00,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
3,3,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,pm25,7.31,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
4,4,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-22T23:45:00.000Z,2020-06-23T05:15:00+05:30,o3,0.82,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."

In [6]:
dfs = [chennai_df, delhi_df, mumbai_df, patna_df]
complete_city_df = pd.concat(dfs)
complete_city_df.head()

,Unnamed: 0,location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution
0,0,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,no2,3.27,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
1,1,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,so2,3.85,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
2,2,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,co,1010.00,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
3,3,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,pm25,6.35,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
4,4,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,o3,0.00,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."

In [7]:
# Merge DataFrames

# FOURcities_merged_df = FOURcities_mergedf.drop('country_x_x', 3)
# FOURcities_merged_df.head()

Summary Table - Cities: Mumbai, Delhi, Chennai, Patna

Cities: Mumbai, Delhi, Chennai, Patna
Statistical Distributions: Mean, Median, Range, Stvd, SEM, IQR
Pollutants (values): PM25
Cross Sectional Dates: * PreCOVID 2017 - EX: 6/22/2017 COVID Present - EX: 6/22/2020

In [8]:
df_pm25 = complete_city_df.loc[complete_city_df['parameter'] == 'pm25']
df_pm25.head()

,Unnamed: 0,location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution
3,3,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:30:00.000Z,2020-06-23T05:00:00+05:30,pm25,6.35,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
6,6,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T23:00:00.000Z,2020-06-23T04:30:00+05:30,pm25,8.15,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
14,14,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T22:45:00.000Z,2020-06-23T04:15:00+05:30,pm25,8.15,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
16,16,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T22:30:00.000Z,2020-06-23T04:00:00+05:30,pm25,8.61,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
23,23,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-22T21:15:00.000Z,2020-06-23T02:45:00+05:30,pm25,7.87,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."

In [9]:
 # If the data is in a dataframe, we use pandas to give quartile calculations pm25

grouped_cities_pm25_df = df_pm25.groupby(["city"])
# grouped_cities_df.head()


avg_value = grouped_cities_pm25_df["value"].mean()
# avg_value.head()


median_value = grouped_cities_pm25_df["value"].median()
# median_value.head()


var_value = grouped_cities_pm25_df["value"].var()
# var_value.head()
std_value = grouped_cities_pm25_df["value"].std()
# std_value.head()
sem_value = grouped_cities_pm25_df["value"].sem()
# sem_value.head()
 
citystats_pm25_df = pd.DataFrame({"Mean":avg_value, "Median":median_value,"Standard Deviation": std_value, "Variance":var_value, "SEM":sem_value})
citystats_pm25_df

              Mean  Median  Standard Deviation    Variance       SEM
city
Chennai  27.321500  19.990           19.315284  373.080203  4.319029
Delhi    28.513824  31.170           15.044580  226.339394  2.580124
Mumbai   10.485556   8.855            5.047283   25.475061  1.189656
Patna     6.456667   6.760            2.345991    5.503673  0.511937

Calculate IQR for prep Box Plot

In [10]:
df = new_df.loc[new_df["cities"]] == "pm25"


quartiles = temperatures.quantile([.25,.5,.75])
lowerq = quartiles[0.25]
upperq = quartiles[0.75]
iqr = upperq-lowerq

print(f"The lower quartile of temperatures is: {lowerq}")
print(f"The upper quartile of temperatures is: {upperq}")
print(f"The interquartile range of temperatures is: {iqr}")
print(f"The the median of temperatures is: {quartiles[0.5]} ")

lower_bound = lowerq - (1.5*iqr)
upper_bound = upperq + (1.5*iqr)
print(f"Values below {lower_bound} could be outliers.")
print(f"Values above {upper_bound} could be outliers.")


temperature_df = pd.read_csv('../Resources/lax_temperature.csv')
temperatures = temperature_df['HourlyDryBulbTemperature']

NameError: name 'new_df' is not defined

Box Plot of PM25 (y-axis) in each city (x-axis) on 4/1/2020

In [14]:
temperatures = temperature_df['HourlyDryBulbTemperature']

fig1, ax1 = plt.subplots()
ax1.set_title('PM25 Levels in Cities')
ax1.set_ylabel('PM25 levels)')
ax1.boxplot(temperatures)
plt.show()

NameError: name 'temperature_df' is not defined

Pie Chart the pollutants (NO2, SO2, PM25, CO, O3 ) in each city

In [15]:
groupby_sex = merged_df.groupby(["Mouse ID","Sex"])
groupby_sex

# Syntax: dataframe.size
# Return : Returns size of dataframe/series which is equivalent to total number of elements. That is rows x columns.
mouse_sex_df = pd.DataFrame(groupby_sex.size())

# Create the df with total count of Female and Male mice
#  use groupby by sex to count the amount of males and female mice 
final_mouse_sex = pd.DataFrame(mouse_sex_df.groupby(["Sex"]).count())
final_mouse_sex.columns = ["Total Count"]

# format the % of female vs male
final_mouse_sex["Percentage of Sex"] = (100*(final_mouse_sex["Total Count"]/final_mouse_sex["Total Count"].sum()))

# format the "Percentage of Sex" column
final_mouse_sex["Percentage of Sex"] = final_mouse_sex["Percentage of Sex"]
# Run to check code 
final_mouse_sex

# Generate a pie plot showing the distribution of female versus male mice using pandas 
#plot = name of the data frame .plot.pie (sumplots true)
colors = ['teal', 'yellow']
explode = (0.2, 0)
plot = mouse_gender.plot.pie(y="Total Count",figsize=(6,6), colors = colors, startangle=140, explode = explode, shadow = True, autopct="%1.1f%%")

NameError: name 'merged_df' is not defined

Scatter Plot [Group selected city]'s PM25 levels throughout day 


*  **Date:** [*Group selected date with sufficient PM25 datapoint]*
*  **Determine time range for parts of day:** Morning [time range EX 12:00 am - 7:59 am?], \
    Midday [time range EX 8:00 am- 3:59 pm], Evening [time range EX 4:00pm -11:59pm]
*  **Axis:** X-value: time; y-value: mean PM25 within time of day

In [18]:
# The maximum x value for our chart will be 100
x_limit = 100

# List of values from 0 to 100 each value being 1 greater than the last
x_axis = np.arange(0, x_limit, 1)

# Create a random array of data that we will use for our y values
data = [random.random() for value in x_axis]  In [4]:  # Tells matplotlib that we want to make a scatter plot
# The size of each point on our plot is determined by their x value
plt.scatter(x_axis, data, marker="o", facecolors="red", edgecolors="black",
            s=x_axis, alpha=0.75)  Out [4]:  <IPython.core.display.Javascript object>  Out [4]:  <matplotlib.collections.PathCollection at 0x110a26da0> In [11]:  # The y limits of our scatter plot is 0 to 1
plt.ylim(0, 1)  Out [11]:  (0, 1) In [5]:  # The x limits of our scatter plot is 0 to 100
plt.xlim(0, x_limit)  Out [5]:  (0, 100) In [6]:  # Prints the scatter plot to the screen
plt.show()

SyntaxError: invalid syntax (<ipython-input-18-ac301bf09a29>, line 8)