#Dataset - March 25, 2020 to June 23, 2020 vs March 25, 2018 to June 23, 2018, First strict lockdown - March 25th, lockdown ended - May 3rd

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [1]:
#Dependencies
import pandas as pd
import numpy as np
import matplotlib as plt
import time
import io
import os
import csv

Read each individual city CSV

In [2]:
chennai_df = pd.read_csv('chennai_data.csv')

In [3]:
delhi_df = pd.read_csv('delhi_data.csv')

In [4]:
mumbai_df = pd.read_csv('mumbai_data.csv')

In [5]:
patna_df = pd.read_csv('patna_data.csv')

Test Dataframe with header

In [6]:
chennai_df.head()

,Unnamed: 0,location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution
0,0,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T01:30:00.000Z,2020-06-24T07:00:00+05:30,no2,2.25,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
1,1,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T01:30:00.000Z,2020-06-24T07:00:00+05:30,o3,31.70,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
2,2,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T01:30:00.000Z,2020-06-24T07:00:00+05:30,pm25,17.97,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
3,3,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T01:30:00.000Z,2020-06-24T07:00:00+05:30,so2,2.87,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."
4,4,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T01:30:00.000Z,2020-06-24T07:00:00+05:30,co,940.00,µg/m³,13.005219,80.239812,"[{""name"":""Central Pollution Control Board"",""ur..."

In [7]:
patna_df.head()

,Unnamed: 0,location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution
0,0,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T00:45:00.000Z,2020-06-24T06:15:00+05:30,pm25,14.52,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
1,1,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T00:45:00.000Z,2020-06-24T06:15:00+05:30,co,1060.00,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
2,2,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T00:45:00.000Z,2020-06-24T06:15:00+05:30,o3,5.59,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
3,3,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T00:45:00.000Z,2020-06-24T06:15:00+05:30,no2,0.00,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
4,4,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T00:45:00.000Z,2020-06-24T06:15:00+05:30,so2,0.00,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."

Merge DataFrames

In [8]:
# Combine the data into a single dataset
chennaidelhi_merged_df = pd.merge(chennai_df, delhi_df,
                                 on ='utc')
mumbaipatna_merged_df = pd.merge(mumbai_df, patna_df,
                                 on ='utc')
FOURcities_merged_df = pd.merge(chennaidelhi_merged_df, mumbaipatna_merged_df,
                                 on ='utc')
FOURcities_merged_df.head()

,Unnamed: 0_x_x,location_x_x,city_x_x,country_x_x,utc,local_x_x,parameter_x_x,value_x_x,unit_x_x,latitude_x_x,...,location_y_y,city_y_y,country_y_y,local_y_y,parameter_y_y,value_y_y,unit_y_y,latitude_y_y,longitude_y_y,attribution_y_y
0,20,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T00:30:00.000Z,2020-06-24T06:00:00+05:30,co,1070.0,µg/m³,13.005219,...,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T06:00:00+05:30,co,0.0,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
1,20,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T00:30:00.000Z,2020-06-24T06:00:00+05:30,co,1070.0,µg/m³,13.005219,...,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T06:00:00+05:30,so2,0.0,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
2,20,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T00:30:00.000Z,2020-06-24T06:00:00+05:30,co,1070.0,µg/m³,13.005219,...,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T06:00:00+05:30,pm25,0.0,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
3,20,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T00:30:00.000Z,2020-06-24T06:00:00+05:30,co,1070.0,µg/m³,13.005219,...,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T06:00:00+05:30,no2,0.0,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."
4,20,"Velachery Res. Area, Chennai - CPCB",Chennai,IN,2020-06-24T00:30:00.000Z,2020-06-24T06:00:00+05:30,co,1070.0,µg/m³,13.005219,...,"Govt. High School Shikarpur, Patna - BSPCB",Patna,IN,2020-06-24T06:00:00+05:30,o3,0.0,µg/m³,25.592539,85.227158,"[{""name"":""Central Pollution Control Board"",""ur..."

In [17]:
FOURcities_merged_df = FOURcities_mergedf.drop('country_x_x', 3)
FOURcities_merged_df.head()

NameError: name 'FOURcities_mergedf' is not defined

Summary Table - 
**Cities:** Mumbai, Delhi, Chennai, Patna 

*   **Cities:** Mumbai, Delhi, Chennai, Patna 
*   **Statistical Distributions:**
Mean, Median, Range, Stvd, SEM, IQR 
*   **Pollutants (values)**: NO2, SO2, PM25, CO, O3


* **Cross Sectional Dates: *** PreCOVID 2017 - EX: 6/22/2017
COVID Present - EX: 6/22/2020

In [ ]:
 # If the data is in a dataframe, we use pandas to give quartile calculations

grouped_drugreg_df = merged_df.groupby(["Drug Regimen"])

avg_drug = grouped_drugreg_df["Tumor Volume (mm3)"].mean()
avg_drug.head()
median_drug = grouped_drugreg_df["Tumor Volume (mm3)"].median()
median_drug.head()
var_drug = grouped_drugreg_df["Tumor Volume (mm3)"].var()
var_drug.head()
std_drug = grouped_drugreg_df["Tumor Volume (mm3)"].std()
std_drug.head()
sem_drug = grouped_drugreg_df["Tumor Volume (mm3)"].sem()
sem_drug.head()
 
drugstats_df = pd.DataFrame({"Mean":avg_drug, "Median":median_drug,"Standard Deviation": std_drug, "Variance":var_drug, "SEM":sem_drug})
drugstats_df

    
    
    
    
    
quartiles = temperatures.quantile([.25,.5,.75])
lowerq = quartiles[0.25]
upperq = quartiles[0.75]
iqr = upperq-lowerq

print(f"The lower quartile of temperatures is: {lowerq}")
print(f"The upper quartile of temperatures is: {upperq}")
print(f"The interquartile range of temperatures is: {iqr}")
print(f"The the median of temperatures is: {quartiles[0.5]} ")

lower_bound = lowerq - (1.5*iqr)
upper_bound = upperq + (1.5*iqr)
print(f"Values below {lower_bound} could be outliers.")
print(f"Values above {upper_bound} could be outliers.")


temperature_df = pd.read_csv('../Resources/lax_temperature.csv')
temperatures = temperature_df['HourlyDryBulbTemperature']

Box Plot of PM25 (y-axis) in each city (x-axis) on 4/1/2020

In [ ]:


temperatures = temperature_df['HourlyDryBulbTemperature']

fig1, ax1 = plt.subplots()
ax1.set_title('PM25 Levels in Cities')
ax1.set_ylabel('PM25 levels)')
ax1.boxplot(temperatures)
plt.show()

Pie Chart the pollutants (NO2, SO2, PM25, CO, O3 ) in each city

In [ ]:
groupby_sex = merged_df.groupby(["Mouse ID","Sex"])
groupby_sex

# Syntax: dataframe.size
# Return : Returns size of dataframe/series which is equivalent to total number of elements. That is rows x columns.
mouse_sex_df = pd.DataFrame(groupby_sex.size())

# Create the df with total count of Female and Male mice
#  use groupby by sex to count the amount of males and female mice 
final_mouse_sex = pd.DataFrame(mouse_sex_df.groupby(["Sex"]).count())
final_mouse_sex.columns = ["Total Count"]

# format the % of female vs male
final_mouse_sex["Percentage of Sex"] = (100*(final_mouse_sex["Total Count"]/final_mouse_sex["Total Count"].sum()))

# format the "Percentage of Sex" column
final_mouse_sex["Percentage of Sex"] = final_mouse_sex["Percentage of Sex"]
# Run to check code 
final_mouse_sex

# Generate a pie plot showing the distribution of female versus male mice using pandas 
#plot = name of the data frame .plot.pie (sumplots true)
colors = ['teal', 'yellow']
explode = (0.2, 0)
plot = mouse_gender.plot.pie(y="Total Count",figsize=(6,6), colors = colors, startangle=140, explode = explode, shadow = True, autopct="%1.1f%%")

Scatter Plot [Group selected city]'s PM25 levels throughout day 


*  **Date:** [*Group selected date with sufficient PM25 datapoint]*
*  **Determine time range for parts of day:** Morning [time range EX 12:00 am - 7:59 am?], Midday [time range EX 8:00 am- 3:59 pm], Evening [time range EX 4:00pm -11:59pm]
*  **Axis:** X-value: time; y-value: mean PM25 within time of day

In [ ]:
# The maximum x value for our chart will be 100
x_limit = 100

# List of values from 0 to 100 each value being 1 greater than the last
x_axis = np.arange(0, x_limit, 1)

# Create a random array of data that we will use for our y values
data = [random.random() for value in x_axis]  In [4]:  # Tells matplotlib that we want to make a scatter plot
# The size of each point on our plot is determined by their x value
plt.scatter(x_axis, data, marker="o", facecolors="red", edgecolors="black",
            s=x_axis, alpha=0.75)  Out [4]:  <IPython.core.display.Javascript object>  Out [4]:  <matplotlib.collections.PathCollection at 0x110a26da0> In [11]:  # The y limits of our scatter plot is 0 to 1
plt.ylim(0, 1)  Out [11]:  (0, 1) In [5]:  # The x limits of our scatter plot is 0 to 100
plt.xlim(0, x_limit)  Out [5]:  (0, 100) In [6]:  # Prints the scatter plot to the screen
plt.show()